### ISSUE TITLE
Add rust-raspi3-tutorial ?

### ISSUE THREAD

**Issue by andre-richter** [rust-embedded/docs#16]
In the meantime, my micro-tutorial collection for doing bare-metal embedded Rust stuff on the `AArch64` based RaspberryPI3 grew to 14 tutorials as of date.

https://github.com/rust-embedded/rust-raspi3-tutorial

Would it be a candidate to list on the docs page?

CC @rust-embedded/resources

**Comment by yerke** [comment]
l took liberty to open a PR, even though there was no response here. I hope it's OK.

**Comment by andre-richter** [comment]
Thanks a lot, much appreciated! 

I totally forgot about this one.
